apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: {{ .Values.services.voter.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: voter
    type: roost-example
  ports:
  - name: http
    port: {{ .Values.httpServicePort}}
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
  namespace: {{ .Values.namespace }}
  labels:
    roost.ai/fitness.git-type: github
    roost.ai/fitness.git-repo-name: voting_app
    roost.ai/fitness.git-org: roost-io
    roost.ai/fitness.git-branch: roost-eaas
    roost.ai/fitness.git-test-path: service-test-suite.voter
    roost.ai/fitness.test-type: cypress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: roost-example
  template:
    metadata:
      labels:
        app: voter
        type: roost-example
    spec:
      containers:
      - name: voter
        image: '{{- printf "%s/%s:%s" .Values.registry .Values.services.voter.imageName .Values.tag -}}'
        stdin: true
        tty: true
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: "{{ .Values.namespace }}.{{ .Values.services.ballot.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
        - name: REACT_APP_EC_SERVER_ENDPOINT
          value: "{{ .Values.namespace }}.{{ .Values.services.ecserver.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
        ports:
        - containerPort: 80
