
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: {{ .Values.services.voter.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: voter
    type: roost-example
  ports:
  - name: http
    port: {{ .Values.httpServicePort}}
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
  namespace: {{ .Values.namespace }}
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: roost-example
  template:
    metadata:
      labels:
        app: voter
        type: roost-example
    spec:
      containers:
      - name: voter
        image: '{{- printf "%s/%s:%s" .Values.registry .Values.services.voter.imageName .Values.tag -}}'
        stdin: true
        tty: true
        env:
        - name: BALLOT_ENDPOINT
        {{- if eq .Values.ballot_endpoint "" }}
          value:  "http://{{ .Values.services.ballot.serviceName }}.{{ .Values.namespace }}.svc.cluster.local" 
        {{- else }}
          value: "{{ .Values.ballot_endpoint }}"
        {{- end }}
        - name: EC_SERVER_ENDPOINT
        {{- if eq .Values.ecserver_endpoint "" }}
          value: "http://{{ .Values.services.ecserver.serviceName }}.{{ .Values.namespace }}.svc.cluster.local"
        {{- else }}
          value: "{{ .Values.ecserver_endpoint }}"
        {{- end }}
        ports:
        - containerPort: 3000
