apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ballot
  name: ballot
spec: 
  selector: 
    app: ballot
  ports:
  - port: 8080
    targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: vivekklp/ballot:latest
        ports:
        - containerPort: 8080
