apiVersion: v1
kind: Service
metadata: 
  name: ecserver
spec: 
  selector: 
    app: ecserver
  ports:
  - port: 8081
    targetPort: 8081
    # nodePort: 30081
  externalTrafficPolicy: Local
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecserver
  template:
    metadata:
      labels:
        app: ecserver
    spec:
      containers:
      - name: ecserver
        image: vivekklp/ecserver:latest
        ports:
        - containerPort: 8081
